### ISSUE TITLE
Error in `Idents<-`: ! 'value' must be a factor or vector

### ISSUE THREAD

**Issue by XIANZHE-LI** [saeyslab/nichenetr#284]
nichenet_output_agnostic <- nichenet_seuratobj_aggregate(
+   seurat_obj = DCM, 
+   sender = "undefined",
+   receiver = "CM", 
+   condition_colname = "group",
+   condition_oi = "DCM",
+   condition_reference = "healthy donor",
+   expression_pct = 0.05,
+   ligand_target_matrix = ligand_target_matrix,
+   lr_network = lr_network,
+   weighted_networks = weighted_networks,
+   top_n_ligands = 80,
+   top_n_targets = 500,
+   lfc_cutoff = 0.1,
+   assay_oi = "RNA"
+ )
[1] "Read in and process NicheNet's networks"
[1] "Define expressed ligands and receptors in receiver and sender cells"
[1] "Perform DE analysis in receiver cell"
Error in `Idents<-`:
! 'value' must be a factor or vector

seurate V5

**Comment by ShiweiHePH** [comment]
I also found this problem(seurate V5)

[1] "Read in and process NicheNet's networks"
[1] "Define expressed ligands and receptors in receiver and sender cells"
[1] "Perform DE analysis in receiver cell"
Error in `Idents<-`:
! 'value' must be a factor or vector

**Comment by csangara** [comment]
Hi,

Can both of you check that your NicheNet version is 2.1.5? This issue should have been fixed in #198, but it's possible that I overlooked some lines of code.

**Comment by XIANZHE-LI** [comment]
> Hi,
> 
> Can both of you check that your NicheNet version is 2.1.5? This issue should have been fixed in #198, but it's possible that I overlooked some lines of code.

![image](https://github.com/user-attachments/assets/c82800ae-5827-4729-aca5-38a043ff91c0)

**Comment by Shubhra1994** [comment]
same issue here!

**Comment by csangara** [comment]
I still can't figure out what's going wrong here. If anyone could provide me with the following, it will be very helpful.

- Their `sessionInfo()`
- The version of their Seurat object: `seuratObj@version`
- The exact line the code malfunctions when following the [step-by-step vignette](https://github.com/saeyslab/nichenetr/blob/master/vignettes/seurat_steps.md)

**Comment by wang0430** [comment]
Did you manage to solve it? My version is 2.2.0, and the issue still persists
